### PR TITLE
Add CI job and SMELT/DASHBOARD url to job settings

### PR DESCRIPTION
**Pull request by mimi1vx**
See https://progress.opensuse.org/issues/109512

### CODE REVIEW

**Review by okurz — APPROVED** [review]
Very nice

**Review by Martchus — APPROVED** [review]
Looks generally good but we should wait until https://github.com/os-autoinst/openQA/pull/4598 is deployed. This also shows that you haven't fully tested it, so how did you test it?

**Comment by mimi1vx** [comment]
@Martchus local run and check results, not tested against openQA .. what openQA do with settings isn't something which bot +- cares

**Comment by Martchus** [comment]
@mimi1vx Ok, but this means that no products will be scheduled until the next OSD deployment (which will contain my PR).

**Pull request merged**
