### PR TITLE
Mark missing jobs as obsolete in QEM dashboard

### PR DESCRIPTION
**Pull request by Martchus**
Related ticket: https://progress.opensuse.org/issues/126551

### CODE REVIEW

**Comment by Martchus** [comment]
Note that the CI check passes locally (with a slightly older requests version but otherwise the same versions). I don't know why it doesn't pass in the CI. The failing request is supposed to be mocked but this apparently doesn't work.

**Comment by okurz** [comment]
I could reproduce the CI problem in an ubuntu container as well as a Tumbleweed container so the interesting question is really why it can even work for you :)

**Comment by perlpunk** [comment]
Reproduced with requests==2.31.0, but passing with requests==2.30.0
So something changed in requests that make the responses mocking fail

**Comment by Martchus** [comment]
I've just reproduced it locally on the master branch. So the failure is definitely unrelated to my changes. Maybe it would be useful to downgrade urllib3 for now within our CI.

**Review by okurz — APPROVED** [review]

**Review by kraih — APPROVED** [review]

**Review by perlpunk — APPROVED** [review]

**Pull request merged**
