### PR TITLE
Switch kernel-azure QEMU VMs to virtio GPU

### PR DESCRIPTION
**Pull request by mdoucha**
HyperV (virtio) GPU is the video device that will be used by kernel-azure in production environment. Switch to it in QEMU tests.

### CODE REVIEW

**Review by Martchus — APPROVED** [review]
It would be nice to include a bugref in the commit message for additional context. Otherwise it looks good as far as I can tell.

**Review by okurz — COMMENTED** [review]
I don't think these settings should go into the source code of qem-bot. Can you not put those into medium settings?

**Comment by mdoucha** [comment]
We use the same medium for kernel-azure, kernel-default and kernel-livepatch. Everything except kernel-azrue should use the default Bochs GPU instead. Ideally, these settings (including `AZURE=1` and `KGRAFT=1` should go into the bot config YAML but it seems that the bot doesn't support such complex logic.

**Comment by okurz** [comment]
I think a "machine" in openQA would work better for such setting. How about defining this in a new machine and use that in job templates?

**Comment by mdoucha** [comment]
> I think a "machine" in openQA would work better for such setting. How about defining this in a new machine and use that in job templates?

I don't see how to change machine for kernel-azure tests without either introducing a completely new flavor or breaking aarch64 kernel-default tests.

**Pull request merged**
